### ISSUE TITLE
Makefile is missing

### ISSUE THREAD

**Issue by ep4sh** [walkrist/goalgs#1]
Hola @walkrist 
I was hopeless at finding Makefile in this repository, but it looks like this amazing project definitely needs one.
I can suggest including the creation of some phony targets for **linting** your code, do you consider implementing it?
I'll be happy to help you with it any time.

**Comment by walkrist** [comment]
Hi @ep4sh 
I've added Makefile with go vet target, but I'm not sure how to implement linting. Would be great if you give me a clue on it

**Comment by walkrist** [comment]
Hi @ep4sh 
Thanks to your guidance I've managed to integrate golangci-lint and some additional checks (via single Makefile) to my CI workflow

**Comment by belovi** [comment]
Closing this one as fixed

**Comment by walkrist** [comment]
Closing this one as fixed
